"""Changed video table

Revision ID: 9b9e7fe032af
Revises: 0953edb6c46a
Create Date: 2023-06-12 16:39:36.683192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b9e7fe032af'
down_revision = '0953edb6c46a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('watches_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'watches_count')
    # ### end Alembic commands ###
